version: '3.1'

services:

  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_DATABASE: shorten_link
      MYSQL_USER: myuser
      MYSQL_PASSWORD: 123456789
